# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08181ddb7e5cd9e372cf5f5cb9d65a6ec70e6c73b88f8ea15da1b24e5f9ad893ae34fed483e3113440d09c91ec1c9ea62ee094d63a4c6d1fb0c8fe621dd7e2b0

test:
  secret_key_base: 2f4509d2508a0378e1cacb00e740024749faecc08af2ab7efd1355ae33d18273a5ab1d415453893f7fdee53fedfc0843b3765965f609ae2706c42ba307f43b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
